!python cli.py fit \
    --trainer.gpus=1         \
    --trainer.max_epochs=40 \
    --trainer.default_root_dir='logs/mlp_mixer' \
    --trainer.log_every_n_steps=5 \
    --model.model_name="mixer" \
    --model.optimizer="adam" \
    --model.learning_rate=0.001 \
    --model.num_classes=5 \
    --data.data_dir="/content/Pytorch_practice/DL/Flower Classification/data/flower_photos" \
    --data.batch_size=32 \
    --wandb_project_name="Flower Classification" \
    --wandb_task_name="MLP Mixer" \
    --use_wandb